name: Security Scan - TruffleHog

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  trufflehog-scan:
    name: Scan for Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Permet à TruffleHog de scanner TOUT l'historique de tes commits

      - name: TruffleHog OSS Scan
        uses: trufflesecurity/trufflehog-actions@main
        with:
          path: ./
          base: ""
          head: "main"